### ISSUE TITLE
Sample code: no dimension for the sheet of paper

### ISSUE THREAD

**Issue by dyamihuyana** [NeoSmartpen/Android-SDK2.0#12]
Hello,
I am working on your SDK and getting familiar with the sample code provided.
I am using a NeoSmartPen N2, on a samsung galaxy S2, android Version 7.0
For now I am only working with the 8x15cm booklet that is provided with the pen.
I am working with AndroidSDK2.0

I would like to re-use the sample code to add a background, an be able to write on top of that background. Unfortunately, the code does not provide the page's width and height.
Specifically:

In MainActivity.java, lines 853-856: no problem, I get the intent's extras.
In SampleView:changePage(), lines 172-176: the calls to MetaDataCtrl.getPageWidth/Height/MarginLeft/Marginight all return 0.

How can I make it so that I have the correct page values?

Thank you very much.

**Comment by dyamihuyana** [comment]
Hello,
I am working on a pocket book (601) and we ordered some A4 IdeaPads (book 609).
I will upload the section/owner i of the pocketbook in a few hours.

**Comment by mrlove1** [comment]
Hi dyamihuyana,

I attatch Nproj file and background image.

[note_601_jpg_img_180110081126.zip](https://github.com/NeoSmartpen/AndroidSDK2.0/files/1934013/note_601_jpg_img_180110081126.zip)
[note_0609.zip]
(https://github.com/NeoSmartpen/AndroidSDK2.0/files/1934014/note_0609.zip)

Thanks.
Best Regards,
Moosaeng Lim

**Comment by dyamihuyana** [comment]
Hello,
I downloaded the zip you provided and put the nproj and background files at the path given by Const.SAMPLE_FOLDER_PATH.
The sample code works well on the first page of the 601 booklet (we haven't received the 609 IdeaPads), but crashes if I write on page 2.

**Comment by mrlove1** [comment]
I am sorry for late reply.

Some notes have the same background for all pages.
Or have the same pattern background.

It is separated by the "extra_info" entry in the file.

For example, Note 609 or 601 have  the same background for all pages.
<extra_info>pdf_page_count=1</extra_info>

So the file imagePath of all pages are equally "3_27_601_1.jpg","3_27_609_1.jpg".

Sometimes one have even number pattern.("Ring Note"603)
"extra_info" entry of  603 Note is "pdf_page_count=2".
The imagePath for odd number pages is "3_27_603_1.jpg".
And the imagePath for even number pages is "3_27_603_2.jpg".

Thanks.
Best Regards,
Moosaeng Lim
