### ISSUE TITLE
Sample Code: Data save and dimension of paper JPG should create manually

### ISSUE THREAD

**Issue by dhanmix14** [NeoSmartpen/Android-SDK2.0#13]
Hello,
I have download sample code and have notebook 
sectionId=3
ownerId=27
noteId=601
pageId=1
[ Below Link i have downloaded the nproj in which only single JPG i.e(only for first page jpg is provided 3_27_601_1.jpg). https://github.com/NeoSmartpen/AndroidSDK2.0/files/1934013/note_601_jpg_img_180110081126.zip ]

So For 64 pages we have just make a clone of first page and rename it?

AND 

Second issue While writing the data on notepad its reflect on Android Device But moving on to second page and again revert to first page Data get clear.

Help me out
Thanks

**Comment by Deokbin** [comment]
Hello,
Thank you for inquiry.

1) In case of note id 601, All pages have the same background.
So you can just use a clone of first page and renamed it.
Or to reduce capacity, you can use same image without page breaks.

2) In sample app, we did not consider for multiple pages. It is just for show rendering.
For multiple pages, you should to development appropriate for your app's UX(list, card view and etc.).

I hope this helps.
Thanks

**Comment by dhanmix14** [comment]
Hello,
Thanks for helping,

In NeoSampleService.java file there is commented part 
i.e

private final class DotConsumerForDBThread extends Thread{
		private int dotCount = 0;
		private int eraserDotCount = 0;

		private int currentSectionId = -1;
		private int currentOwnerId = -1;
		private int currentBookcodeId = -1;
		private int currentPageId = -1;
		//ActionController mActionController;

		private ArrayList<Dot> dotArray = new ArrayList<Dot>(100);

//		private ArrayList<Dot> eraserDotArray = new ArrayList<Dot>(100);

		public DotConsumerForDBThread(Context context) {
			super();
//			mActionController = ActionController.getInstance(context);
		}
}


If i remove comment " ActionController ",  ActionController class doesn't exist, I think in this class only data are stored so while retrieving the data again we can view the data fetch from sqllite

Can you provide ActionController.java?

Thanks

**Comment by Deokbin** [comment]
Hello,

ActionController class is no longer used.
You have to implement it yourself.

I'm sorry I can not help you.

Thanks.
