### ISSUE TITLE
Sample code usage issue

### ISSUE THREAD

**Issue by kukaraditya** [NeoSmartpen/Android-SDK2.0#14]
Hello
We have recently purchased NeoPen and would like to now develop our inhouse app for the same. I have downloaded the sample code Android SDK2.0 and I am able to connect the pen successfully . 

But I am unable to do following . So would need help to achieve it -
When whatever I write on Page 1 (note pad provided with neopen) , It reflects on the mobile screen. Then I turn to page2 and the app identifies the same. But when I return back to Page1 and starts writing on it, the previous data doesn't show on the mobile screen. Can anyone help me with the code on restoring back the previously written data ?

Thanks

**Comment by Deokbin** [comment]
Hello,
Thank you for inquiry.

In sample app, we did not consider for multiple pages. It is just for show rendering.
For multiple pages, you should to develop appropriate for your app's UX(list, card view and etc.).

I hope this helps.
Thanks
