### ISSUE TITLE
Using Myscript with Neosmartpen 2.0 android SDK

### ISSUE THREAD

**Issue by Jai1601** [NeoSmartpen/Android-SDK2.0#15]
Greetings team NeoLab,

i have been working on neosmartpen android 2.0 sample app and i need to convert handwritten strokes to text using myscript but i couldn't find any sample or resource guide to connect MyScript Sdk with this sample.
Could you please help out to achieve it.

Thanks and regards
Jai Singh Hada

**Comment by Deokbin** [comment]
Hello, 

Thanks for your inquiry.
I am sorry that we didn't have the sample code or guide.
Please contact representantive of MyScript SDK.

Thanks and regards.
