### ISSUE TITLE
Set the pen led color

### ISSUE THREAD

**Issue by boehm-e** [NeoSmartpen/Android-SDK2.0#22]
Hi,

I see at [PenCommAgent.cs#L232](https://github.com/Chinmayrane16/Windows-Interface-for-Interacting-with-Neo-SmartPen-NWP-F110/blob/366577f360eefb81a87ecc5fdc56ddbb84ddfc08/AuroniaDemoApp/PenCommAgent.cs#L232) and at [PenCommV2.cs#L1120](https://github.com/Chinmayrane16/Windows-Interface-for-Interacting-with-Neo-SmartPen-NWP-F110/blob/366577f360eefb81a87ecc5fdc56ddbb84ddfc08/Neosmartpen.Net.Protocol.v2/Neosmartpen/Net/Protocol/v2/PenCommV2.cs#L1120) that is is possible to change the LED color programmatically with the windows SDK.
I dont see any mention of this feature in the Android SDK. How to achieve the same result ?
Thank you

**Comment by toyadarong** [comment]
@boehm-e 
Hi boehm-e.

Single Pen
[PenCtrl.java#L488](https://github.com/NeoSmartpen/Android-SDK2.0/blob/master/NASDK2.0_Studio/app/src/main/java/kr/neolab/sdk/pen/PenCtrl.java#L488)

Multi Pen [MultiPenCtrl.java#L552](https://github.com/NeoSmartpen/Android-SDK2.0/blob/162f10e161a3a7aa24adc192324577db048318d4/NASDK2.0_Studio/app/src/main/java/kr/neolab/sdk/pen/MultiPenCtrl.java#L552)

**Comment by boehm-e** [comment]
Hi,
 I thought this method was to control the pen color and not the LED.
Thanks
